name: Create Release with Binary
on:
  push:
    branches:
      - master

jobs:
  create_release_with_binary:
    name: Create Release with Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Build Go Application
        run: GOOS=linux GOARCH=amd64 go build -o etherfi-sync-client-linux-amd64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: master
          release_name: v1.0.1
          draft: false
          prerelease: false
  
      - name: Upload Binary to Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/octet-stream" \
            --data-binary "@etherfi-sync-client-linux-amd64" \
            "${{ steps.create_release.outputs.release_url }}/assets?name=etherfi-sync-client-linux-amd64"
