name: Create Release with Binary
on:
  push:
    branches:
      - 'v1*'

jobs:
  create_release_with_binary:
    name: Create Release with Binary
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.17'

      - name: Build Go Application Arm
        run: GOOS=linux GOARCH=arm64 go build -o etherfi-sync-client-linux-arm64

      - name: Build Go Application Amd
        run: GOOS=linux GOARCH=arm64 go build -o etherfi-sync-client-linux-amd64

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Print everything out
        run: ls

      - name: Zip arm!
        run: tar -czvf etherfi-sync-client-linux-arm64.tar.gz -C . etherfi-sync-client-linux-arm64

      - name: Zip amd!
        run: tar -czvf etherfi-sync-client-linux-amd64.tar.gz -C . etherfi-sync-client-linux-amd64

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: |
            ./etherfi-sync-client-linux-amd64.tar.gz
            ./etherfi-sync-client-linux-arm64.tar.gz
          asset_name: |
            etherfi-sync-client-linux-amd64.tar.gz
            etherfi-sync-client-linux-arm64.tar.gz
          asset_content_type: |
            application/tar+gzip
            application/tar+gzip