name: Release

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Build and package
        run: |
          go build -o myprogram -ldflags="-s -w" ./main.go
          tar -czvf myprogram_linux_amd64.tar.gz myprogram

      - name: Create Release
        uses: wangyoucao577/go-release-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            myprogram_linux_amd64.tar.gz
          tagName: v1.0.0  # Replace with your desired tag name
          releaseTitle: Release v1.0.0
          goos: linux
          goarch: amd64 